### ISSUE TITLE
disabling connected standby breaks sleep

### ISSUE THREAD

**Issue by tx46** [distantorigin/XPS-Enhancements#2]
## steps to reproduce:

1. disable connected standby
2. enable hibernation
3. reboot
4. wait until computer enters hibernation
5. start computer

## expected results:

computer starts normally

## actual results:

fans turn on, screen remains black

## more info

disabling connected standby seems to be the culprit:

https://www.reddit.com/r/Dell/comments/8bhryl/help_dell_xps_13_9360_wont_wake_from_sleep/

(i re-enabled connected standby and the problem went away)

**Comment by distantorigin** [comment]
I'll test this out and update the guide accordingly.

**Comment by distantorigin** [comment]
It apparently took decades, but connected standby has been removed from the guide. Sorry about this taking ages.
